// Copyright XGrids, Inc. All Rights Reserved.
// Shader cache version tag. Do not remove.
// SHADER_VERSION 1

#include "/Engine/Public/Platform.ush"

uint SplatSize;
uint NodeNum;
uint TotalCount;
float3 CameraPosition;
float3 CameraForward;
float ImportScale;
float4x4 LocalToClip;
float FrustumMargin;
uint GroupCountX;
ByteAddressBuffer SplatBuffer;
RWBuffer<uint> IndexBuffer;
RWBuffer<uint> SortKeys;
ByteAddressBuffer SortParameter;
RWByteAddressBuffer CullCounter;

[numthreads(THREADS_X, 1, 1)]
void MainSortKey(
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadID : SV_GroupThreadID,
    uint3 GroupID : SV_GroupID,
    uint GroupIndex : SV_GroupIndex)
{
    LIXEL_LCC2_GENKEY_IMPLE
}
